### GET /
GET http://localhost:3000/

### Get all media items
GET http://localhost:3000/media

### GET /items/:id
GET http://localhost:3000/media/9625

### POST /items
POST http://localhost:3000/media
content-type: application/json

{
      "media_id": 0,
      "filename": "0.jpg",
      "filesize": 0,
      "title": "Zero",
      "description": "First item added",
      "user_id": 0,
      "media_type": "image/jpeg",
      "created_at": "22.11.2023"
    }

### Put item by id works
PUT http://localhost:3000/media/0
content-type: application/json

{
  "title": "New TTTTTTTTTTTT"
}

### DELETE item by id works
DELETE http://localhost:3000/media/0

//taa inja

### PUT /items/:id
PUT http://localhost:3000/api/items/6
content-type: application/json

{"name": "updated omena"}



### USERS ###
### GET all users
GET http://localhost:3000/api/user

### GET user by id
GET http://localhost:3000/api/user/305

### POST /api/user
POST http://localhost:3000/api/user
content-type: application/json

{
    "username": "new username",
    "password": "new password",
    "email": "new email"
}

### PUT /api/user/:id
PUT http://localhost:3000/api/user/260
content-type: application/json
{
    "username": "updated username",
    "password": "updated password"
}

### DELETE /api/user/:id
DELETE http://localhost:3000/api/user/305



### MEDIA ###
### GET all media items
GET http://localhost:3000/api/media

### GET media by id
GET http://localhost:3000/api/media/9632

### POST /api/media
POST http://localhost:3000/api/media
content-type: application/json
{
  "filename": "kdh4.jpg",
  "title": "New image",
  "description": "The description of the new image",
  "user_id": 305,
  "media_type": "image/jpeg"
}

### PUT /api/media/:id
PUT http://localhost:3000/api/media/9626
content-type: application/json
{
  "title": "Basement modified",
  "description": "Some new description"
}

### DELETE /api/media/:id
DELETE http://localhost:3000/api/media/9626