### GET /
GET http://localhost:3000/

### Get all media items
GET http://localhost:3000/media

### POST item to media
POST http://localhost:3000/media
Content-Type: application/json

{
      "filename": "alfa.jpg",
      "title": "1",
      "description": "alfa item added"
}

### GET Item from media by id
GET http://localhost:3000/media/24

### PUT Item worked
PUT http://localhost:3000/media/26
Content-Type: application/json

{
      "filename": "a.jpg",
      "title": "1aaaaaaaä",
      "description": "ald"
}

### DELETE item by id works
DELETE http://localhost:3000/media/26

### USERS ###
### GET all users Works
GET http://localhost:3000/user

### POST /user works
POST http://localhost:3000/user
content-type: application/json

  {
    "username": "post user",
    "password": "uhits passwords"
  }


### GET user by id works
GET http://localhost:3000/user/3


### PUT /user/:id Worked!
PUT http://localhost:3000/user/3
content-type: application/json

{
    "username": "updated username",
    "password": "updated password"
}

### DELETE user woorks
DELETE http://localhost:3000/user/3